http:
  routers:
    dashboard:
      service: api@internal
      middlewares:
        - "bashboard-auth"
      rule: "Host(`dashboard.gaoqiaoxue.com`)"
    Aseries-Apis:
      service: Aseries-Apis-Service
      middlewares:
        - "corsHeaders"
      rule: "Host(`aseries-apis.gaoqiaoxue.com`)"
    Aseries-Admin:
      service: Aseries-Admin-Service
      middlewares:
        - "corsHeaders"
      rule: "Host(`aseries-admin.gaoqiaoxue.com`)" 
    Meilisearch:
      service: Meilisearch-Service
      middleware:
      rule: "Host(`search.gaoqiaoxue.com`)"
  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
    bashboard-auth:
      basicAuth:
        users:
          - "zihuang2010:$apr1$TqSDfaM6$G54MEXx9yNu5C/VTF5KVB0"
    corsHeaders:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "x-requested-with"
          - "content-type"
          - "Authorization"
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - POST
          - PUT
          - DELETE
        accessControlAllowOriginList:
          - "*"
        accessControlExposeHeaders:
          - "refresh-token"
        accessControlMaxAge: 100
        addVaryHeader: true
  services:
    Aseries-Apis-Service:
      loadBalancer:
        servers:
          - url: "http://172.18.0.10:9501"
    Aseries-Admin-Service:
      loadBalancer:
        servers:
          - url: "http://172.18.0.11:9501"
    Meilisearch-Service:
      loadBalancer:
        servers:
          - url: "http://172.18.0.21:7700"
tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
