version: '3.3'

services:
  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: elastic
    restart: always
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - bootstrap.memory_lock=true
      - transport.host=0.0.0.0
      - transport.tcp.port=9300
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - discovery.type=single-node
      - node.name=es1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      proxy:
        ipv4_address: 172.18.0.21

networks:
  proxy:
    external: true
